### ISSUE TITLE
@dr-chain do we need to add specific security consideration about entropy in the browser for wallet generation ?

### ISSUE THREAD

**Issue by gregLibert** [massalabs/massa-standards#45]
@dr-chain do we need to add specific security consideration about entropy in the browser for wallet generation ?

_Originally posted by @gregLibert in https://github.com/massalabs/massa-standards/pull/44#discussion_r1172232277_

**Comment by dr-chain** [comment]
@gregLibert We can but I don't think we need it in `Wallet <> DApp communication` since it is just a communication standard (please correct me if I am wrong here).

Maybe, the security considerations (more appropriately - requirements) about entropy when the wallet is generated by a browser extension can be part of another standard.

**Comment by Ben-Rey** [comment]
@gregLibert What about this issue ?

**Comment by gregLibert** [comment]
In my opinion, this task should be prioritized before conducting any wallet audits. However, since we currently don't have any internal wallets that are browser extensions, it might be wise to seek guidance from @damip .

**Comment by damip** [comment]
As modern browsers deal a lot with cryptography and sensitive information, they are expected to have good entropy using `https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues`.

I don't think a standard should specify how to get good random values because it varies from platform to platform and from one language to another, just that they need to be cryptographically secure.

That being said, a general guideline for JS users could be:

In JS, don't use [Math.random()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random) which is not cryptographically secure, use [window.crypto.getRandomValues()](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues) .
